services:
    franken:
        container_name: "wsc_frankenphp_franken"
        build:
            context: .
            dockerfile: setup/frankenphp/Dockerfile
        volumes:
            - '.:/var/www/franken/'
        ports:
            - '8010:80'
        environment:
            CADDY_ADAPTER: caddyfile
            CADDY_CONFIG: /etc/caddy/Caddyfile
            APP_ENV: dev
            APP_DEBUG: 1
            MERCURE_PUBLISHER_JWT_KEY: '8b52f8e451c03e26f4c79249c6d33476e1c905f2a4795f83e43f6f545a3f708a'
            MERCURE_SUBSCRIBER_JWT_KEY: '8b52f8e451c03e26f4c79249c6d33476e1c905f2a4795f83e43f6f545a3f708a'
            MERCURE_EXTRA_DIRECTIVES: |
                anonymous
                log
        depends_on:
            - db
    worker:
        container_name: "wsc_frankenphp_worker"
        restart: unless-stopped
        build:
            context: .
            dockerfile: setup/frankenphp/Dockerfile
        command: ["frankenphp", "php-cli", "bin/console", "messenger:consume", "async"]
        volumes:
            - '.:/app'
        depends_on:
            - franken
    db:
        image: mysql:8.0
        container_name: "wsc_frankenphp_db"
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysqldata:/var/lib/mysql
volumes:
    mysqldata:
